---
title: "COVID-19 in Chittenden County"
author: "David Howell"
date: "8/11/2020"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
CHITTENDEN_DATA_URL <- "https://services1.arcgis.com/BkFxaEFNwHqX3tAw/arcgis/rest/services/VIEW_EPI_CountyDailyCountTS_PUBLIC/FeatureServer/0/query?where=CNTYGEOID%3D50007&outFields=date,C_New,D_New&returnGeometry=false&outSR=4326&f=json"


getLatestCovidData <- function() {
  res <- httr::GET(CHITTENDEN_DATA_URL)
  jsonlite::fromJSON(httr::content(res, "text"))$features$attributes %>%
    rename(new_cases=C_New, new_deaths=D_New) %>%
    mutate(date = as.POSIXct(date/1000, origin="1970-01-01"))  
}
```

```{r}
covid <- getLatestCovidData()
covid
```


```{r}
ggplot(covid) +
  geom_bar(aes(x=date, y=new_cases), stat='identity', color='gray') +
  labs(x="Date", y="New Cases", title="COVID-19 in Chittenden Count, VT") +
  theme_classic()
```
```{r}
ggplot(covid) +
  geom_bar(aes(x=date, y=new_deaths), stat='identity', color='gray') +
  labs(x="Date", y="New Cases", title="COVID-19 in Chittenden Count, VT") +
  theme_classic()
```

```{r}
ggplot(covid) +
  geom_bar(aes(x=date, y=new_cases), stat='identity', color='gray') +
  geom_line(aes(x=date, y=cumsum(new_cases)), color="gray") +
  labs(x="Date", y="New Cases", title="COVID-19 in Chittenden Count, VT") +
  theme_minimal()
```

```{r}
ggplot(covid) +
  geom_bar(aes(x=date, y=new_deaths), stat='identity', color='gray') +
  geom_line(aes(x=date, y=cumsum(new_deaths)), color="gray") +
  labs(x="Date", y="New Deaths", title="COVID-19 in Chittenden Count, VT") +
  theme_minimal()
```
